---
title: "Purifying "
output: pdf_document
---

The Southern Annular Mode (SAM) is the main mode of variability in the Southern Hemisphere and it impacts several important aspects of the hemispheric circulation, such as persistent blocking, Rossby wave propagation, and local  anomalies of temperature an precipitation. Most authors describe it as a zonally symmetric pattern, a fact that is reflected not only in its name, but also in the various methods used to characterise it. Of the several different indices presented in the literature, many of them are based on zonal means of sea level pressure or geopotential height. However, if one computes composites and regression patterns based on them, they consistently result in zonally assymetric patterns partially embebed in a zonally symmetric structure. Here, we propose a straightforward method of creating two sister indices of Symemtric and Asymmetric SAM and show that they can be used to separate between the zonally symmetric and asymmetric structure. At each level, we first separate the geopotntial pattern associated with SAM into its zonally symemtric and asymmetric components and then project the observed monthly geopotential anomalies on each of them to contstruct two indices. Regression patterns based on the asymetric index are almost totally zonally asymmetrical and viceversa. The Asymmetric SAM in the troposphere is associated with equivalent barotropic planetary waves 3, 2 and 1 to a lesser extent, while in the stratosphere is almost totally dominated by baroclinic planetary wave 1. The tropospheric asymmetric signal is not correlated with the stratospheric asymmetric signal, while the respective symemtric signals show greater troposphere-stratosphere connection. The tropospheric Asymmetric SAM is associated with temperature and precipitation anomalies in boreal Spring and Summer, some of which are not evident in the traditional SAM index. Since we also show that the observed trend towards more positive SAM in the troposphere is completely explained by the Symmetric component, we argue that this methodology can be useful when trying to connect long-term trends to SAM variabilty. 




```{r eval=FALSE, include=FALSE}
nchar(gsub(" ", "", "The Southern Annular Mode (SAM) is the main mode of variability in the Southern Hemisphere and it impacts several important aspects of the hemispheric circulation, such as persistent blocking, Rossby wave propagation, and local  anomalies of temperature an precipitation. Most authors describe it as a zonally symmetric pattern, a fact that is reflected not only in its name, but also in the various methods used to characterise it. Of the several different indices presented in the literature, many of them are based on zonal means of sea level pressure or geopotential height. However, if one computes composites and regression patterns based on them, they consistently result in zonally assymetric patterns partially embebed in a zonally symmetric structure. Here, we propose a straightforward method of creating two sister indices of Symemtric and Asymmetric SAM and show that they can be used to separate between the zonally symmetric and asymmetric structure. At each level, we first separate the geopotntial pattern associated with SAM into its zonally symemtric and asymmetric components and then project the observed monthly geopotential anomalies on each of them to contstruct two indices. Regression patterns based on the asymetric index are almost totally zonally asymmetrical and viceversa. The Asymmetric SAM in the troposphere is associated with equivalent barotropic planetary waves 3, 2 and 1 to a lesser extent, while in the stratosphere is almost totally dominated by baroclinic planetary wave 1. The tropospheric asymmetric signal is not correlated with the stratospheric asymmetric signal, while the respective symemtric signals show greater troposphere-stratosphere connection. 
The tropospheric Asymmetric SAM is associated with temperature and precipitation anomalies in boreal Spring and Summer, some of which are not evident in the traditional SAM index. Since we also show that the observed trend towards more positive SAM in the troposphere is completely explained by the Symmetric component, we argue that this methodology can be useful when trying to connect long-term trends to SAM variabilty. "))
```

